plugins {
    id 'java'
    id 'application'
}

group = 'com.chesspairing'
version = '0.2.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.chesspairing.web.ChessPairingApplication'
}

dependencies {
    runtimeOnly 'com.mysql:mysql-connector-j:8.4.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
